import { Ionicons } from '@expo/vector-icons';
import { StyleSheet, Text, View } from 'react-native';
import { MetricCard } from '../../components/MetricCard';
import { Screen } from '../../components/Screen';
import { SectionCard } from '../../components/SectionCard';
import { useAuth } from '../../providers/AuthProvider';
import { colors } from '../../theme';
export function HomeScreen() { const { user } = useAuth(); return <Screen><View style={styles.top}><View><Text style={styles.muted}>GOOD MORNING</Text><Text style={styles.greeting}>{user?.name ?? 'Farmer'} 👋</Text></View><View style={styles.avatar}><Ionicons name="notifications-outline" size={22} color={colors.forest}/></View></View><SectionCard style={styles.weather}><View><Text style={styles.weatherEyebrow}>TODAY’S WEATHER</Text><Text style={styles.temp}>28°</Text><Text style={styles.weatherText}>Partly cloudy · Vijayawada</Text></View><View style={styles.weatherSide}><Ionicons name="partly-sunny" size={48} color="#FFE484"/><Text style={styles.rain}>Rain tomorrow</Text><Text style={styles.weatherText}>Humidity 70%</Text></View></SectionCard><Text style={styles.title}>Farm overview</Text><View style={styles.grid}><MetricCard icon="water-outline" label="Soil moisture" value="58%" detail="Ideal range"/><MetricCard icon="leaf-outline" label="Crop health" value="95%" detail="Healthy" tone="#E8F8C7"/><MetricCard icon="flask-outline" label="Soil pH" value="6.8" detail="NPK normal" tone="#E8F2FF"/><MetricCard icon="speedometer-outline" label="Water tank" value="72%" detail="Sufficient" tone="#FFF3D9"/></View><Text style={styles.title}>Today’s AI advice</Text><SectionCard style={styles.advice}><View style={styles.aiIcon}><Ionicons name="sparkles" size={22} color="#fff" /></View><View style={{ flex: 1 }}><Text style={styles.adviceTitle}>Delay irrigation today</Text><Text style={styles.adviceText}>Rain is likely tomorrow. Your field moisture is already in the ideal range.</Text><Text style={styles.action}>View full recommendation →</Text></View></SectionCard><Text style={styles.title}>Quick actions</Text><View style={styles.actions}>{[['camera-outline','Scan crop'], ['water-outline','Irrigation'], ['cloud-outline','Forecast']].map(([icon, label]) => <View style={styles.actionItem} key={label}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={22} color={colors.green}/><Text style={styles.actionLabel}>{label}</Text></View>)}</View></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, muted: { fontSize: 11, color: colors.muted, fontWeight: '800', letterSpacing: 1 }, greeting: { color: colors.ink, fontSize: 24, fontWeight: '900', marginTop: 3 }, avatar: { width: 44, height: 44, borderRadius: 15, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, weather: { backgroundColor: colors.forest, flexDirection: 'row', justifyContent: 'space-between' }, weatherEyebrow: { color: '#CBEA84', fontSize: 11, fontWeight: '800', letterSpacing: 1 }, temp: { color: '#fff', fontSize: 44, fontWeight: '800', marginTop: 4 }, weatherText: { color: '#DDEEDA', fontSize: 12 }, weatherSide: { alignItems: 'flex-end', justifyContent: 'center', gap: 3 }, rain: { color: '#fff', fontWeight: '800', fontSize: 12 }, title: { color: colors.ink, fontWeight: '900', fontSize: 17, marginTop: 2 }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12 }, advice: { flexDirection: 'row', gap: 13, backgroundColor: '#E8F8C7' }, aiIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.green }, adviceTitle: { color: colors.ink, fontWeight: '900', fontSize: 15 }, adviceText: { color: '#4E6A52', fontSize: 12, lineHeight: 18, marginTop: 3 }, action: { color: colors.green, fontSize: 12, fontWeight: '800', marginTop: 8 }, actions: { flexDirection: 'row', justifyContent: 'space-between' }, actionItem: { width: '31%', alignItems: 'center', backgroundColor: '#fff', borderRadius: 18, paddingVertical: 14, gap: 6 }, actionLabel: { color: colors.ink, fontWeight: '700', fontSize: 11 } });
