import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppButton } from '../../components/AppButton';
import { Screen } from '../../components/Screen';
import { useAuth } from '../../providers/AuthProvider';
import { authService } from '../../services/authService';
import { colors } from '../../theme';
import { UserRole } from '../../types';
const roles: { key: UserRole; title: string; icon: keyof typeof Ionicons.glyphMap }[] = [{ key: 'farmer', title: 'Farmer', icon: 'leaf-outline' }, { key: 'expert', title: 'Expert', icon: 'medical-outline' }, { key: 'government', title: 'Officer', icon: 'business-outline' }, { key: 'admin', title: 'Admin', icon: 'shield-checkmark-outline' }];
export function LoginScreen() {
  const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [role, setRole] = useState<UserRole>('farmer'); const [busy, setBusy] = useState(false); const { signIn } = useAuth();
  const submit = async () => { try { setBusy(true); if (!sent) { await authService.requestOtp(phone); setSent(true); Alert.alert('OTP sent', 'Demo OTP: 123456'); } else await signIn(await authService.verifyOtp(phone, otp, role)); } catch (e) { Alert.alert('Unable to continue', e instanceof Error ? e.message : 'Try again.'); } finally { setBusy(false); } };
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Screen><View style={styles.hero}><View style={styles.logo}><Ionicons name="leaf" size={32} color="#fff" /></View><Text style={styles.title}>Welcome to AgriShield</Text><Text style={styles.subtitle}>Your intelligent partner for every field.</Text></View><Text style={styles.heading}>Continue as</Text><View style={styles.roles}>{roles.map(item => <View key={item.key} style={[styles.role, role === item.key && styles.selected]} onTouchEnd={() => setRole(item.key)}><Ionicons name={item.icon} size={22} color={role === item.key ? '#fff' : colors.green} /><Text style={[styles.roleText, role === item.key && { color: '#fff' }]}>{item.title}</Text></View>)}</View><Text style={styles.heading}>{sent ? 'Verify your number' : 'Mobile number'}</Text><View style={styles.input}><Ionicons name={sent ? 'key-outline' : 'call-outline'} size={20} color={colors.green} /><TextInput value={sent ? otp : phone} onChangeText={sent ? setOtp : setPhone} keyboardType="number-pad" placeholder={sent ? 'Enter 6-digit OTP' : '+91 98765 43210'} maxLength={sent ? 6 : 15} style={styles.inputText} /></View><AppButton title={busy ? 'Please wait…' : sent ? 'Verify & Continue' : 'Send OTP'} onPress={submit} /><View style={styles.divider}><View style={styles.line}/><Text style={styles.or}>OR</Text><View style={styles.line}/></View><AppButton title="Continue with Google" variant="outline" onPress={() => Alert.alert('Coming soon', 'Connect this button to Firebase Google Sign-In.')} /><Text style={styles.note}>By continuing, you agree to AgriShield’s Terms & Privacy Policy.</Text></Screen></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ hero: { alignItems: 'center', paddingVertical: 24, gap: 8 }, logo: { height: 68, width: 68, borderRadius: 23, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.ink, fontWeight: '800', fontSize: 25 }, subtitle: { color: colors.muted, fontSize: 14 }, heading: { color: colors.ink, fontWeight: '800', fontSize: 15, marginTop: 4 }, roles: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, role: { width: '47%', height: 72, padding: 12, borderRadius: 16, gap: 5, borderWidth: 1, borderColor: colors.border, backgroundColor: '#fff' }, selected: { backgroundColor: colors.green, borderColor: colors.green }, roleText: { color: colors.ink, fontWeight: '700', fontSize: 13 }, input: { height: 54, borderRadius: 16, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.border }, inputText: { flex: 1, fontSize: 16, color: colors.ink }, divider: { flexDirection: 'row', alignItems: 'center', gap: 10 }, line: { height: 1, backgroundColor: colors.border, flex: 1 }, or: { color: colors.muted, fontSize: 11, fontWeight: '700' }, note: { color: colors.muted, textAlign: 'center', fontSize: 11, lineHeight: 16, marginTop: 2 } });
